spring:
  config:
    activate:
      on-profile: local
---
spring:
 config:
  activate:
   on-profile: local
  datasource:
    url: jdbc:h2:mem:online_bank
h2:
    console:
      enabled: true
      path: /h2-console
jpa:
    hibernate:
      ddl-auto: create
server:
  port: 9091

kafka:
  bootstrap-servers: localhost:9092
consumer:
    group-id: account_group	
auto-offset-reset: earliest
key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
properties:
        spring.json.value.default.type: com.Banking.Retail_Banking.models.Account 
spring.json.trusted.packages: "*"
key-serializer: org.apache.kafka.common.serialization.StringSerializer
value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
transaction-id-prefix: tx-
listener:
   concurrency: 3
security:
user:
 name:  owner
 password: password 
 web:
      security:
        basic:
          enabled: true 
app:
 kafka:
  topic: account








